export const REQUEST_USER_LOGIN = 'REQUEST_USER_LOGIN';
export const SUCCESS_USER_LOGIN = 'SUCCESS_USER_LOGIN';
export const SUCCESS_USER_FB_LOGIN = 'SUCCESS_USER_FB_LOGIN';

export const REQUEST_STORE_DATA = 'REQUEST_STORE_DATA';
export const FETCH_STORE_DATA = 'FETCH_STORE_DATA';
export const FAILURE_STORE_DATA = 'FAILURE_STORE_DATA';

export const REQUEST_STORE_DETAIL = 'REQUEST_STORE_DETAIL';
export const SUCCESS_STORE_DETAIL = 'SUCCESS_STORE_DETAIL';



